apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::679753243804:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::679753243804:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KD7R1N5NBXAX
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn:  arn:aws:iam::679753243804:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KD7R1N5NBXAX\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n- rolearn: arn:aws:iam::679753243804:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2020-06-19T23:08:50Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl.exe
    operation: Update
    time: "2020-06-20T16:09:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "61384"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: db9e410a-1a8f-4e88-9e1e-6780c4674c29
