apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn:  arn:aws:iam::679753243804:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KD7R1N5NBXAX
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::679753243804:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
